### ISSUE TITLE
different node version

### ISSUE THREAD

**Issue by phamdt** [premma/myDockerFiles#1]
hi, thanks for sharing this. i tried running your protractor-headless but i needed to specify versions for everything. for example, the node version, the protractor version, etc. i'm running into an issue with node 5.3 where xvfb errors. specifically:
`xvfb-run: error: Xvfb failed to start`

any ideas?

**Comment by premma** [comment]
Hello Phamdt, i am glad you tried that. Few of my friends tried my docker,too. They have reported, that it works flawlessly. But they did not specify versions of node or other packages. May I ask why you need to do so? Is it because of your project, that needs special versions or is it because it would not build the docker?
 f it would be the second case, I would recommend to download working docker from docker hub. But I guess, it is not that simple, right? :-) 

I hope we will find a solution and help others, who would have similar troubles like you.

**Comment by premma** [comment]
Also, please include all the changes you have tried to make, so I could try to reproduce the problem myself. Thanks.

**Comment by phamdt** [comment]
for now, i'd like to see if i can get your image working as is. i've changed the run command to specify port 3000 since on my mac, i'm running my application on 3000. then, from my protractor folder inside of my application directory, i run the command.

docker run -it --rm --net=host -p 127.0.0.1:3000:3000 -v /dev/shm:/dev/shm -v $(pwd):/protractor premma/protractor-headless <my protractor config file which happens to be in this same folder>.

this produces the following error:

```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver

/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:174
      callback(new Error(message));
               ^
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:174:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketErrorListener (_http_client.js:262:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1246:8)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at [object Object].Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/lib/driverProviders/driverProvider.js:42:27)
    at [object Object].Runner.createBrowser (/usr/local/lib/node_modules/protractor/lib/runner.js:190:37)
    at /usr/local/lib/node_modules/protractor/lib/runner.js:280:21
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
[launcher] Process exited with error code 1
```

so this error makes me think that i need to change my protractor config since it's expected something running directly on my localhost.

previous config:

```
exports.config = {
  // The address of our running selenium server.
  seleniumAddress: 'http://localhost:4444/wd/hub',

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'firefox'
  },

  specs: ['specs/myspec.js'],

  baseUrl: 'http://localhost:3000',


  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 50000
  }
};
```

so i change seleniumAddress from `'http://localhost:4444/wd/hub'` to my docker-machine's ip for the domain and leave the port. that doesn't work either as it raises the same type of error.

**Comment by premma** [comment]
great, please comment the whole line with webdriver and browser capabilities settings:

```
exports.config = {
  // The address of our running selenium server.
  // seleniumAddress: 'http://localhost:4444/wd/hub',

  // Capabilities to be passed to the webdriver instance.
//  capabilities: {
//    'browserName': 'firefox'
//  },

```

and try again. the protractor inside runs it's own webdriver and headless chrome browser. 

and the run it again with the same command.
Good luck!

**Comment by phamdt** [comment]
ah, that did it. thanks for the quick response.

**Comment by premma** [comment]
your welcome... Is there anything else I could help you with?

**Comment by phamdt** [comment]
oh, i have new strange errors. so it appears to be running the spec, but one of the specs is failing even though when i run protractor locally, it passes. it's probably something for me to figure out but i thought i'd leave this comment in case anyone else reads this.

**Comment by premma** [comment]
ok.. it may be caused by the differences between chrome and firefox... Is that possible?
I will leave this issue unsloved, until you figure that out.

**Comment by phamdt** [comment]
i am curious if that is an issue at some point, but i actually ran the test locally on chrome as well.

**Comment by premma** [comment]
I was getting the same results on both local protractor and dockered one.. But we are in the early phase of testing, so we have about 30 test scenarios only.

**Comment by phamdt** [comment]
another thing that is interesting is that error in your image is at the selenium level not at the protractor level: 

```
Selenium standalone server started at http://10.0.2.15:45806/wd/hub
Started

/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
NoSuchElementError: no such element: Unable to locate element: {"method":"link text","selector":"Sign up"}
  (Session info: chrome=48.0.2564.116)
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.1.12-boot2docker x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 114 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
System info: host: 'default', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.1.12-boot2docker', java.version: '1.7.0_95'
*** Element info: {Using=link text, value=Sign up}
Session ID: ffa8f3bc11607ab7589f4400720222cb
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.op5Hkb, chromedriverVersion=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=48.0.2564.116, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
    at new bot.Error (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)
    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:379:20
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
    at process._tickCallback (node.js:402:9)
From: Task: WebElement.click()
    at [object Object].webdriver.WebDriver.schedule (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:362:15)
    at [object Object].webdriver.WebElement.schedule_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1817:23)
    at [object Object].webdriver.WebElement.click (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1920:15)
    at signUp (/protractor/specs/angular-express-spec.js:26:56)
    at Object.<anonymous> (/protractor/specs/angular-express-spec.js:58:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
[launcher] Process exited with error code 1
```

**Comment by premma** [comment]
well, this looks like an issue to selenium itself. As i can see, they recommend to visit url `http://seleniumhq.org/exceptions/no_such_element.html` to see, what you are dealing with. I am using the latest version. i hope. I may check and rebulid the docker. But if you will excuse me, I will return to this issue later. You always are welcome to try to buld the docker yourself.. just put the Dockerfile and the shell script in one directory and run `docker build -t name_your_docker .`
 It will surely load the lastest selenium and chrome

**Comment by phamdt** [comment]
ya, out of curiousity, i ran the same spec with the original webnicer version. same thing. anyhow, i think you've already been helpful and i can figure out the rest. feel free to close this issue.

**Comment by premma** [comment]
ok.. thank you. If you find the docker helpful, please leave me like in docker hub. :-) It wish you find the bug soon!
